config/routes.rb
Rails.application.routes.draw do
  root 'series#index'
  # Rutas para Series
  get '/series', to: 'series#index', as: 'series'
  get '/series/new', to: 'series#new', as: 'new_serie'
  post '/series', to: 'series#create'
  get '/series/:id', to: 'series#show', as: 'serie'
  get '/series/:id/edit', to: 'series#edit', as: 'edit_serie'
  patch '/series/:id', to: 'series#update'
  delete '/series/:id', to: 'series#destroy'

  # Rutas para Películas
  get '/peliculas', to: 'peliculas#index', as: 'peliculas'
  get '/peliculas/new', to: 'peliculas#new', as: 'new_pelicula'
  post '/peliculas', to: 'peliculas#create'
  get '/peliculas/:id', to: 'peliculas#show', as: 'pelicula'
  get '/peliculas/:id/edit', to: 'peliculas#edit', as: 'edit_pelicula'
  patch '/peliculas/:id', to: 'peliculas#update'
  delete '/peliculas/:id', to: 'peliculas#destroy'

  # Rutas para Documentales
  get '/documentales', to: 'documentales#index', as: 'documentales'
  get '/documentales/new', to: 'documentales#new', as: 'new_documental'
  post '/documentales', to: 'documentales#create'
  get '/documentales/:id', to: 'documentales#show', as: 'documental'
  get '/documentales/:id/edit', to: 'documentales#edit', as: 'edit_documental'
  patch '/documentales/:id', to: 'documentales#update'
  delete '/documentales/:id', to: 'documentales#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/documental.rb
class Documental < ApplicationRecord
    validates :name, :synopsis, :director, presence: true
  end
  

app/models/pelicula.rb
class Pelicula < ApplicationRecord
  validates :name, :synopsis, :director, presence: true
end

app/models/series.rb
class Series < ApplicationRecord
    validates :name, :synopsis, :director, presence: true
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documentales_controller.rb
class DocumentalesController < ApplicationController
  def index
    @documentales = Documental.all
  end

  def create
    @documental = Documental.new(documental_params)
    if @documental.save
      redirect_to documentales_path, notice: 'Documental creado exitosamente.'
    else
      render :new
    end
  end

  def new
    @documental = Documental.new
  end

  private

  def documental_params
    params.require(:documental).permit(:name, :synopsis, :director)
  end
end

app/controllers/peliculas_controller.rb
class PeliculasController < ApplicationController
  def index
    @peliculas = Pelicula.all
  end

  def create
    @pelicula = Pelicula.new(pelicula_params)
    if @pelicula.save
      redirect_to peliculas_path, notice: 'Película creada exitosamente.'
    else
      render :new
    end
  end

  def new
    @pelicula = Pelicula.new
  end

  private

  def pelicula_params
    params.require(:pelicula).permit(:name, :synopsis, :director)
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  def index
    @series = Series.all
  end

  def create
    @serie = Serie.new(serie_params)
    if @serie.save
      redirect_to series_path, notice: 'Serie creada exitosamente.'
    else
      render :new
    end
  end

  def new
    @serie = Serie.new
  end

  private

  def serie_params
    params.require(:serie).permit(:name, :synopsis, :director)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documentales_helper.rb
module DocumentalesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/peliculas_helper.rb
module PeliculasHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/documentales/create.html.erb
<h1>Documentales#create</h1>
<p>Find me in app/views/documentales/create.html.erb</p>

app/views/documentales/index.html.erb
<h1>Listado de Documentales</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Sinopsis</th>
      <th>Director</th>
    </tr>
  </thead>
  <tbody>
    <% @documentales.each do |documental| %>
      <tr>
        <td><%= documental.name %></td>
        <td><%= documental.synopsis %></td>
        <td><%= documental.director %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Agregar Documental', new_documental_path, class: 'btn btn-primary' %>

app/views/documentales/new.html.erb
<h1>Agregar Documental</h1>

<%= form_with(model: @documental, url: documentales_path) do |form| %>
  <div>
    <%= form.label :name, 'Nombre' %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :synopsis, 'Sinopsis' %>
    <%= form.text_area :synopsis %>
  </div>

  <div>
    <%= form.label :director, 'Director' %>
    <%= form.text_field :director %>
  </div>

  <%= form.submit 'Guardar' %>
<% end %>

<%= link_to 'Volver al listado', documentales_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="/">MovieApp</a>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Series', series_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Películas', peliculas_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Documentales', documentales_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>


    <div class="container mt-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/peliculas/create.html.erb
<h1>Peliculas#create</h1>
<p>Find me in app/views/peliculas/create.html.erb</p>

app/views/peliculas/index.html.erb
<h1>Listado de Películas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Sinopsis</th>
      <th>Director</th>
    </tr>
  </thead>
  <tbody>
    <% @peliculas.each do |pelicula| %>
      <tr>
        <td><%= pelicula.name %></td>
        <td><%= pelicula.synopsis %></td>
        <td><%= pelicula.director %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Agregar Película', new_pelicula_path, class: 'btn btn-primary' %>

app/views/peliculas/new.html.erb
<h1>Agregar Película</h1>

<%= form_with(model: @pelicula, url: peliculas_path) do |form| %>
  <div>
    <%= form.label :name, 'Nombre' %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :synopsis, 'Sinopsis' %>
    <%= form.text_area :synopsis %>
  </div>

  <div>
    <%= form.label :director, 'Director' %>
    <%= form.text_field :director %>
  </div>

  <%= form.submit 'Guardar' %>
<% end %>

<%= link_to 'Volver al listado', peliculas_path %>

app/views/series/create.html.erb
<h1>Series#create</h1>
<p>Find me in app/views/series/create.html.erb</p>

app/views/series/index.html.erb
<h1>Listado de Series</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Sinopsis</th>
      <th>Director</th>
    </tr>
  </thead>
  <tbody>
    <% @series.each do |serie| %>
      <tr>
        <td><%= serie.name %></td>
        <td><%= serie.synopsis %></td>
        <td><%= serie.director %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Agregar Serie', new_serie_path, class: 'btn btn-primary' %>

app/views/series/new.html.erb
<h1>Nueva Serie</h1>

<%= form_with(model: @serie, url: series_path) do |form| %>
  <div>
    <%= form.label :name, 'Nombre' %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :synopsis, 'Sinopsis' %>
    <%= form.text_area :synopsis %>
  </div>

  <div>
    <%= form.label :director, 'Director' %>
    <%= form.text_field :director %>
  </div>

  <%= form.submit 'Guardar' %>
<% end %>

<%= link_to 'Volver al listado', series_path %>